spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fxdealsdb
    username: postgres
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  flyway:
    baseline-on-migrate: true